title: oneil.dev
author: coneil
subtitle: Regurgitating the Internet

url: "https://coneil.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/coneil"
footer_text: "I hadn't considered there would be a footer."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
